name: docker4640

on:
  push:
    branches: 
      - 'main'
    
jobs:
  secrets-github:
    runs-on: windows-latest
    steps:
      - name: Echo
        run: |
          echo ${{secrets.DOCKER_HUB_USERNAME }} | sed 's/./& /g'
          echo ${{secrets.DOCKER_HUB_TOKEN }} | sed 's/./& /g'
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: Richard2000wang
          password: dckr_pat_99x8EWMVeKxYDspL_oO_qWjC0KI
      - name: Build and push
        uses: docker/build-push-action@v3
        with: 
          push: true
          tags: richard2000wang/app2:app2
